version: 2
jobs:
  test:
    machine:
      image: circleci/node@3.0.0
      docker_layer_caching: true
    working_directory: ~/repo
          
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo yum update -y 
            npm install --save react-router react-mdl
            npm start

  build:
  
    machine:
      image: circleci/node@3.0.0
      docker_layer_caching: true
    working_directory: ~/resume-router-k8s
          
    steps:
      - checkout 
      - run:
          name: build image
          command: |
            docker build -t $DOCKERHUB_USERNAME/resume-router-k8s .
 
  push:
    machine:
      image: circleci/node@3.0.0 
      docker_layer_caching: true
    working_directory: ~/resume-router-k8s 
    steps:
      - checkout 
      - run:
          name: Push image
          command: |
            docker build -t $DOCKERHUB_USERNAME/resume-router-k8s .
            echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/resume-router-k8s 	

workflows:
  version: 2
  build-deploy:
    jobs:
      - test:
          context: DOCKERHUB
          filters:
            branches:
              only: master       
      - build:
          context: DOCKERHUB 
          requires:
            - test
          filters:
            branches:
              only: master
      - push:
          context: DOCKERHUB
          requires:
            - build
          filters:
            branches:
              only: master