apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations: 
    kubernetes.io/ingress.class: nginx
  name: ingress-resource-1
spec:
  rules:
  - host: jaysalpatel.org
    http:
      paths:
      - backend:
          serviceName: nginx-deploy-main
          servicePort: 80
